server:
  listen_port: 8443
  cert_file: "server.crt"
  key_file: "server.key"

mappings:
  - uuid: "550e8400-e29b-41d4-a716-446655440000"
    domain: "site1.example.com"
  - uuid: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
    domain: "site2.example.com"
